export enum EstadoPedido {
  PENDIENTE = 'PENDIENTE',
  VALIDADO = 'VALIDADO',
  PAGADO = 'PAGADO',
  EN_PREPARACION = 'EN_PREPARACION',
  LISTO = 'LISTO',
  EN_ENTREGA = 'EN_ENTREGA',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
}

export enum EstadoPago {
  PENDIENTE = 'PENDIENTE',
  CONFIRMADO = 'CONFIRMADO',
  RECHAZADO = 'RECHAZADO',
  REEMBOLSADO = 'REEMBOLSADO',
}

export enum EstadoEntrega {
  ASIGNADO = 'ASIGNADO',
  EN_CAMINO = 'EN_CAMINO',
  ENTREGADO = 'ENTREGADO',
  FALLIDO = 'FALLIDO',
}

export enum RolUsuario {
  CONSUMER = 'CONSUMER',
  KITCHEN = 'KITCHEN',
  DISPATCHER = 'DISPATCHER',
  VENUE_ADMIN = 'VENUE_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
