services:
  - type: web
    name: concert-orders-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_MODE
        value: local
      - key: PAYMENT_PROVIDER
        value: mock
      - key: CORS_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
